### ISSUE TITLE
OnoSW -> OpSoRo

### ISSUE THREAD

**Issue by StanNotebaert** [OPSORO/OnoSW#9]

**Comment by aaramirezd** [comment]
Hello, I'm trying to start a raspberry pi 2b with jessie 8 (Kernel version:4.4) + OnoSw.
I saw that the tutorial was updated, but I get not even launch the python web server

The access point is well configured, also I can access the network and share the Internet connection

looking at the log file, I have only two errors:
- rsyslogd-2007: action 'action 17' suspended, next retry is
- with "snd_soc_bcm2708_i2s" module

can you help me?
Andrés
